
version: '3.3'
services:
  burgas:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: godgift
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/


  joomla:
    image: joomla
    restart: always
    links:
      - db:mysql
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: root
    ports:
      - 8080:80

  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE:  burgas_web
     MYSQL_USER: burgas
     MYSQL_PASSWORD: Burgas63
    ports:
     - 6033:3306

